version: "3.1"
services:
  mongo:
    hostname: mongo
    container_name: nittak-mongo
    image: mongo:4.0-xenial
    expose: [27017]
    ports: ["28001:27017"]
    restart: always
    networks:
      - nittak-log
  logger:
    hostname: logger
    image: docker.elastic.co/logstash/logstash:7.4.0
    container_name: nittak-logger
    volumes:
       - "./logs/:/usr/share/logstash/logs/"
       - "./pipeline/:/usr/share/logstash/pipeline/"
    command: bash -c "bin/logstash-plugin install logstash-output-mongodb && logstash -f /usr/share/logstash/pipeline/logstash.conf"
    networks:
      - nittak-log
  filebeat:
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:7.4.0
    container_name: nittak-filebeat
    volumes:
      - "./logs/:/usr/share/filebeat/logs/"
      - "./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml"
    networks:
      - nittak-log
networks:
  nittak-log:
    driver: bridge